spring.application.name=ENSAH Gestion Soutenances

# Database H2 (remplacer par MySQL/PostgreSQL en prod)
spring.datasource.url=jdbc:h2:file:./data/soutenances;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Thymeleaf
spring.thymeleaf.cache=false
spring.thymeleaf.encoding=UTF-8

# File upload
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB

# App config
app.soutenance.duree-minutes=60
app.soutenance.heure-debut=8
app.soutenance.heure-fin=18
app.soutenance.jury-size=3

# Logging
logging.level.ma.ensah=DEBUG
